default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mobius_bot_development
  host: localhost
  #min_messages: warning # debug5, debug4, debug3, debug2, debug1, log, notice, warning, error, fatal, and panic

test:
  <<: *default
  database: mobius_bot_test

production:
  <<: *default
